### ISSUE TITLE
type number always generates a integer value

### ISSUE THREAD

**Issue by georgebarbarosie** [pateketrueke/json-schema-faker#10]
The following code would invariably generate an integer:
require("json-schema-faker")({type: "number"});

This can be traced to the use of random(min,max) in lib/types/number.js which in turn uses faker.random.number() with options min and max but no set precision; Faker.js's random.number() function always generates an integer value unless a precision is set in the options.

**Comment by pateketrueke** [comment]
Sorry but I'm not sure about the differences of `integer` and `number` types.

My guess is that `integer` types will never contain a floating point... so, a `number` type may generate integer values also?

Currently `json-schema-faker` also treats as `integer` any `number` type containing `multipleOf`, and i'm still confused on how to proceed about `number`'s meaning.

What do you think?
