### ISSUE TITLE
Extending low-level dependencies

### ISSUE THREAD

**Issue by tkoomzaaskz** [pateketrueke/json-schema-faker#12]
There is one more thing I'd appreciate a lot: extending/parametrizing base libraries (e.g. faker). This is a must-have, when you want to customize it:
 * set the locale, which alters results in the end - faker provides internationalization feature: https://github.com/Marak/faker.js#localization. 
 * extending the library with custom generators, that will make use of all existing features of the library (e.g. custom faker generators will reuse its locale definitions, which is unable using json-schema-faker format functions).

Currently, `jsf` API looks like the following:

    var jsf = require('json-schema-faker');
    var schema = ...
    var sample = jsf(schema);

I'm thinking of adding a `jsf.customize(gen, fn)` function, where `gen` is the generator (faker, chance, etc.) and fn is the callback like the following:

    function customizeFaker(faker) {
        faker.locale = "de"; // or whatever
        faker.customModule = {
            fn_1: function...
            fn_2: function...
            fn_n: function...
        };
        return faker;
    }

Finally, the outside API would look like this:

    var jsf = require('json-schema-faker');
    var schema = ...
    jsf.customize('faker', function(faker){
        faker.locale = "de"; // or whatever
        faker.customModule = {
            fn_1: function...
            fn_2: function...
            fn_n: function...
        };
        return faker;
    });
    var sample = jsf(schema);

Where `customize` is, of course, optional. This would encapsulate extending dependencies, which is impossible now, unfortunately. No matter who and how uses the json-schema-faker, he could add his own stuff. Currently, `faker` is just fetched from npm as-is and loaded using node.js `require` and you can do nothing with it.

I can prepare a PR, but I need to know whether you're opened for such feature.

**Comment by pateketrueke** [comment]
Actually the code responsible of that is `lib/types/string.js` but I think `generate()` function should be moved to `lib/util/generate.js` before for reusability.

Please rebase your work on the `development` branch before, if you can add some specs would be enough to merge.

Also I don't know if chance/randexp can be customized as well, that would be awesome too.

Thanks for your time and interest in jsf.

:beers:

**Comment by tkoomzaaskz** [comment]
So I guess the answer is "yes" :)

Ok, I'll rebase to `development` branch in the first place. Do you accept the API that I suggestes, i.e. the `jsf.customize(...)`?

----

As for [chance.js](https://github.com/victorquinn/chancejs), I haven't seen such thing in the docs, but I don't know this library. I submitted an issue: https://github.com/victorquinn/chancejs/issues/178. I expect this to be exactly the same as faker.js

As for [randexp](https://github.com/fent/randexp.js), I think it's a different approach. RandExp is just a constructor, the created objects can be altered, bt it's not the case:

    var randexp = new RandExp(/random stuff: .+/);
    randexp.defaultRange.subtract(32, 126);
    randexp.defaultRange.add(0, 65535);
    randexp.gen();
    // => random stuff: 湐箻ໜ䫴␩⶛㳸長���邓蕲뤀쑡篷皇硬剈궦佔칗븛뀃匫鴔事좍ﯣ⭼ꝏ䭍詳蒂䥂뽭

**Comment by pateketrueke** [comment]
> So I guess the answer is "yes" :)

Totally a yes, thanks!

> Do you accept the API that I suggestes, i.e. the jsf.customize(...)?

Yeah, the same way as `jsf.formats()` would be fine for `jsf.customize()` I guess.

For `chance.js` I notice they have a `mixin()` method, so it's awesome having support for that.

For `randexp` I see is not necessary.

:beers:

**Comment by tkoomzaaskz** [comment]
The basic idea I'm thinking of now is behind node modules overriding.

`customized.js` file:

```
var _ = require ('underscore');

_.mixin({
  capitalize: function(string) {
    return string.charAt(0).toUpperCase() + string.substring(1).toLowerCase();
  }
});

module.exports = _;
```

`index.js` file:

```
var _ = require('./customized');

console.log(_.capitalize('test'));
```

and the *runtime*:

```
$ node index.js
Test
```

(the thing is that *underscore* doesn't have `_.capitalize` method provided).

**Comment by tkoomzaaskz** [comment]
Going more into dynamic generator level (faker, chance):

`factory.js` file:

```
module.exports = {
  customize: function (genName, fn) {
    // assume generator === "underscore"
    // need to pre-load all generators with browserify
    var gen = require(genName);
    return fn(gen);
  }
};
```

`index.js` file:

```
var factory = require('./factory');

var _ = factory.customize('underscore', function(_){
  _.mixin({
    capitalize: function(string) {
      return string.charAt(0).toUpperCase() + string.substring(1).toLowerCase();
    }
  });
  return _;
});

console.log(_.capitalize('test'));
```

and the *runtime*:

```
$ node index.js
Test
```

**Comment by tkoomzaaskz** [comment]
I think we'll need to re-structure the project a little bit. The problem lies in lack of separation of concerns: modules talk to each other as they wish and it makes difficult to extend any of them.

I listed all occurences of loading `faker` and `chance`:
```
$ grep -rn "require('faker')" .
./node_modules/json-schema-faker/lib/types/object.js:3:var faker = require('faker'),
./node_modules/json-schema-faker/lib/types/string.js:3:var faker = require('faker'),
./node_modules/json-schema-faker/lib/util/random.js:3:var faker = require('faker');
./node_modules/json-schema-faker/README.md:120:require('faker').internet.email();

$ grep -rn "require('chance')" .
./node_modules/json-schema-faker/lib/types/string.js:4:    Chance = require('chance'),
./node_modules/json-schema-faker/node_modules/chance/README.md:110:var Chance = require('chance'),
./node_modules/json-schema-faker/README.md:139:var Chance = require('chance'),
```
Ignoring markdown files, we've got:

* ./node_modules/json-schema-faker/lib/types/object.js
* ./node_modules/json-schema-faker/lib/types/string.js
* ./node_modules/json-schema-faker/lib/util/random.js

The *loading tree* goes more or less like this:

* **object**, **string** -> primitives
* primitives, **random** -> traverse
* index -> traverse

And since we want to provide `jsf.customize`, it could be added into `index.js` just as the `.formats` module is.

This is a work-in-progress, I'll keep on updating.

**Comment by tkoomzaaskz** [comment]
Above commit solves the problem, I've been testing it with running the following file from the console:

```
var fakerExtend = function(faker){
    faker.locale = "de";

    faker.mixin = function(namespace, fnObject){
        faker[namespace] = fnObject;
    };

    faker.mixin('custom', {
      statement: function(length) {
        return faker.name.firstName() + " has " + faker.finance.amount() + " on " + faker.finance.account(length) + ".";
      }
    });

    return faker;
};

//------------------------------------------------------------------------------

var jsf = require('json-schema-faker');

var schema = {
  type: 'object',
  properties: {
    user: {
      type: 'object',
      properties: {
        id: {
            type: 'integer',
            minimum: 0,
            minimumExclusive: true
        },
        name: {
          type: 'string',
          faker: 'name.findName'
        },
        name2: {
          type: 'string',
          faker: {
              'custom.statement': [19]
          }
        },
        email: {
          type: 'string',
          format: 'email',
          faker: 'internet.email'
        }
      },
      required: ['id', 'name', 'name2', 'email']
    }
  },
  required: ['user']
};

jsf.customize('faker', fakerExtend);

var sample = jsf(schema);

console.log(sample);
```

I've got a problem with running tests on my machine (I'm using windows). `npm install` seems to install everything that is needed, but when I run `grunt test:parts && cat generated/lcov.info | coveralls` which I've found in [.travis.yml], I get following error:

```
$ grunt test:parts && cat generated/lcov.info | coveralls

jit-grunt: Plugin for the "clean" task not found.
If you have installed the plugin already, please setting the static mapping.
See https://github.com/shootaroo/jit-grunt#static-mappings

Warning: Task "clean:temp" failed. Use --force to continue.

Aborted due to warnings.


Execution Time (2015-05-06 12:05:36 UTC)
loading tasks  16ms  █████████████████████████████████████████████████████████████████████████ 94%
Total 17ms
```

By the way, this `grunt-parts` seems strange to me, haven't seen it before.

**Comment by tkoomzaaskz** [comment]
By the way, I'm trying to run travis for this branch (it's called `extending-dependencies`, https://github.com/tkoomzaaskz/json-schema-faker/tree/extending-dependencies). I turned the repo `on` in my travis account settings, I've re-pushed the commit (with `-f`, adding just one line of comment). But travis hasn't run yet. Do you know why?

**Comment by pateketrueke** [comment]
How are you testing against these new jsf features?

Did you take a look to the [specs](https://github.com/pateketrueke/json-schema-faker/tree/master/spec)?

I think you should add `spec/core/issues/customize.json` for documenting your features/tests.

Also, [grunt-parts](https://github.com/partsjs/dev-grunt) will lint your code and run the tests for you, etc.

I'll add this to the guidelines. :beers:

**Comment by tkoomzaaskz** [comment]
Well, I've just spent over 2 hours trying to configure tests. I'm afraid, that these are the issues of https://github.com/partsjs/dev-grunt. Do we have to use it in this project? It took me really long to debug, that there is a path conflict that resolve in `path.join` on Windows:

```
cwd: C:\Users\tomasz.ducin\Documents\GitHub\json-schema-faker
jit.pluginsRoot: C:\Users\tomasz.ducin\Documents\GitHub\json-schema-faker\node_m
odules\grunt-parts/node_modules
pluginName: grunt-contrib-clean
tasks: tasks
findPath: C:\Users\tomasz.ducin\Documents\GitHub\json-schema-faker\C:\Users\toma
sz.ducin\Documents\GitHub\json-schema-faker\node_modules\grunt-parts\node_module
s\grunt-contrib-clean\tasks
```

precisely dev-parts.js:

```
  require('jit-grunt')(grunt, map)({
    pluginsRoot: cwd + '/node_modules'
  });
```

where cwd containt `C:\`. Eventually, both jit.pluginsRoot and cwd contain C:\ and it results in conflict.

What do you say to use something more standard and **platform-independent**? I'm a linux guy, but currently I can work on windows only :(

**Comment by tkoomzaaskz** [comment]
not the last build has failed due to https://github.com/lemurheavy/coveralls-public/issues/487

**Comment by pateketrueke** [comment]
I'd started `grunt-parts` due the boilerplate of setup stuff whenever I like to code a npm module (it was born in private projects).

And I like the results, however I never thought on supporting Windows (?) out of the box on development.

> What do you say to use something more standard and platform-independent?

Do you mean `jit-grunt` is not working for you or it's only how `grunt-parts` is using it?

Today I can't work on a Windows machine to fix `grunt-parts` but If you found a fix or something let me know, I'll patch this asap...

**Comment by tkoomzaaskz** [comment]
I don't like Windows but I'm forced to use it, more or less.

The problem is how grunt-parts user jit-grunt. The plugin paths are generated in wrong way.

**Comment by tkoomzaaskz** [comment]
I'm thinking of renaming `customize` to `extend` which sounds better. How do you think @pateketrueke ?

**Comment by pateketrueke** [comment]
Oops!

**Comment by pateketrueke** [comment]
BTW, there is no docs for `customize()` so we can use `extend` and deprecate `0.1.8`?

**Comment by tkoomzaaskz** [comment]
yep, working on it right now ;)

**Comment by tkoomzaaskz** [comment]
#36, #37
@pateketrueke take a look whether we're ready to publish `0.1.9`.

**Comment by pateketrueke** [comment]
Yeah!

I'll merge locally an then publish the next release asap.

**Comment by whitlockjc** [comment]
I'm not seeing this have any impact on the bundle when using browserify.  I set the `locale` to `en` and it seems to still bundle all of the locales in faker.js.  Is there a way to use this new feature to replace `require('faker')` with `require('faker/locale/en')` so I do not get all locales in my browserified bundle?  *(See https://github.com/Marak/faker.js#individual-localization-packages)*  Currently when I run `browserify --list index.js | grep "locale" | wc -l` I'm getting over `840` files related to faker.js locales and that makes my browserified binary huge.  Since I wanted to make sure I wasn't in the wrong before filing a bug, I figured I'd discuss here first.  Here is what I'm doing now, which could be wrong:

```js
/**
 * Helper method to create a JSON Schema Mocker.
 *
 * @param {object} [options] - The mocker options
 * @param {object} [options.formatGenerators] - The custom format generators to use
 *
 * @returns {object} The JSON Schema mocker
 */
module.exports.createJSONSchemaMocker = function (options) {
  /* istanbul ignore if */
  if (_.isUndefined(options)) {
    options = {};
  }

  // Extend faker.js to only include the 'en' locale
  mocker.extend('faker', function (faker) {
    faker.locale = 'en';

    return faker;
  });

  // Add the custom format generators
  _.each(options.formatGenerators, function (handler, name) {
    mocker.formats(name, handler);
  });

  return mocker;
};
```
