### ISSUE TITLE
`number` results in `integer`

### ISSUE THREAD

**Issue by tkoomzaaskz** [pateketrueke/json-schema-faker#13]
I've been trying to generate fake float cash amounts:

    var jsf = require('json-schema-faker');

    var schema = {
      "type": "object",
      "properties": {
        "floatValue": {
          "type": "number",
          "faker": {
            "finance.amount": [0, 1000000, 2]
          }
        }
      },
      "required": [
        "floatValue"
      ]
    };

    var sample = jsf(schema);

    console.log(sample);

Each time, it results in returning a float:

    { floatValue: -60579383 }
    { floatValue: 82403714 }
    { floatValue: -88911564 }
    { floatValue: -91259973 }
    { floatValue: 55329873 }
    { floatValue: -88439479 }
    { floatValue: 26251958 }
    { floatValue: 50581325 }
    { floatValue: -32840326 }

As far as I understand the code, it is due to: https://github.com/pateketrueke/json-schema-faker/blob/master/lib/types/number.js#L8-L31

**Comment by pateketrueke** [comment]
Fixed on `0.1.6`.
