### ISSUE TITLE
providing a jsf UI (online demo)

### ISSUE THREAD

**Issue by tkoomzaaskz** [pateketrueke/json-schema-faker#15]
Use `gh-pages` branch to deploy a `browserify`ed online demo. Moved from #14.

**Comment by tkoomzaaskz** [comment]
I'd start something similar to http://jsonschemalint.com/:
* twitter bootstrap UI
* one textarea for the schema along with fake data definitions
* another textarea for the sample result
* a *generate* button, which will regenerate the sample result
* controllers: angular or vanilla JavaScript

Once we're done with above (which may take a while) we may proceed with other stuff. I guess it's better to start with small things. Does that domain (from the CNAME file) belong to you? Does changing the content of `pateketrueke`/`json-schema-faker`:`gh-pages` automatically trigger the website update?

**Comment by pateketrueke** [comment]
> Does that domain (from the CNAME file) belong to you?

Actually i'm using this: http://dns.js.org/ :+1:

**Comment by tkoomzaaskz** [comment]
please take a look at #19
