### ISSUE TITLE
generating array of integers

### ISSUE THREAD

**Issue by tkoomzaaskz** [pateketrueke/json-schema-faker#30]
I'm trying to generate many integers in an array. I've started with following `fschema` (i.e. *faker schema* :beers:):

```json
{
  "type": "array",
  "minItems": 15,
  "items": {
    "type": "integer"
  }
}
```

`jsf` throws error and crashes: `Uncaught Error: invalid range between: 15, 5 in /`. It is thrown here:

```
  } catch (e) {
    if (e.path) {
      throw new Error(e.message + ' in ' + '/' + e.path.join('/'));
    } else {
      throw e;
    }
  }
```
Unfortunately, the `e.path` is empty and I don't know where it is. Seems like a magic number of value `5` to me. Another thing is *more then minimum*. I try to reduce the `minItems` to 5:

```json
{
  "type": "array",
  "minItems": 5,
  "items": {
    "type": "integer"
  }
}
```
and I get:
```
[
  94859109,
  -13252038,
  -23878120,
  35945246,
  -45816780
]
```
(correct) or
```
[
  94859109,
  -13252038,
  -23878120,
  35945246,
  -45816780
]
```
(correct) or
```
[
  -72862631,
  87917025,
  34045210,
  -39725548,
  -87628962,
  36148999
]
```
(correct) with more than 5 elements. How is the number of elements determined? If you don't get it at first time, just click several times until you get it.

**Comment by pateketrueke** [comment]
> How is the number of elements determined?

The call to `random()` are causing issues internally due the generated range.

https://github.com/pateketrueke/json-schema-faker/blob/master/lib/types/array.js#L55

**Comment by tkoomzaaskz** [comment]
I find it a bug. If `minItems > 5` then we're in trouble.
