### ISSUE TITLE
`Address.city` doesn't appear

### ISSUE THREAD

**Issue by Semigradsky** [pateketrueke/json-schema-faker#42]
I created this schema json:
```json
{
  "title": "User",
  "type": "object",
  "properties": {
    "id": {
      "type": "string",
      "faker": "random.uuid"
    },
    "name": {
      "type": "string",
      "faker": "name.findName"
    },
    "login": {
      "type": "string",
      "faker": "internet.userName"
    },
    "email": {
      "type": "string",
      "format": "email",
      "faker": "internet.email"
    },
    "city": {
      "type": "string",
      "faker": "address.city"
    }
  },
  "required": [
    "id",
    "login",
    "email"
  ]
}
```

After generating 2000 objects I not found no one object with `city` field.
`City` field is appear If remove `id`, `login`, `name` or `email` from schema.

**Comment by pateketrueke** [comment]
I see a nice issue here, if you move the `city` field before the `name` works fine.

I think properties should be shuffled before faking them, also taking in account those properties that are required.

I'll work on improving that behavior asap.

Thanks for your feedback!

**Comment by tkoomzaaskz** [comment]
@Semigradsky the city attribute is not included in the required list. Is that on purpose? This would make 100% it will be included always - but don't know if that's what you want.

**Comment by Semigradsky** [comment]
Yeah I want emulate an optional fields: `name` and `city`.

**Comment by tkoomzaaskz** [comment]
@pateketrueke I can confirm, that optional fields don't behave... in a deterministic way, I would say. When optional, they appear very rarely.

----

I was thinking of a `probability` factor for optional fields. I know this would be another additional property for JSON schemas, but this would solve it completely:


    "city": {
      "type": "string",
      "faker": "address.city"
      "probability": 0.8
    }

If "city" is optional (not present in `required`) then the `probability` is used. What do you think? And if `probability` is undefined, then make it random.

**Comment by Semigradsky** [comment]
> And if `probability` is undefined, then make it random.

`random` meaning `probability === 0.5`?

**Comment by tkoomzaaskz** [comment]
I don't have an opinion on that (randm vs random(random)), there should be a default. Anyway, @pateketrueke hasn't commented this whole idea yet.

**Comment by pateketrueke** [comment]
I was over-thinking this issue but the solution is quite simple:

Given `X` declared `properties` and `Y` defined as `required` we got `Z = X - Y`.

Then we apply a `shuffle()` to `Z`, iterate over `Z.slice(0, random(0, Z.length))` and generate some optional properties, etc.

Also the `random()` call was never taking in account the `Z.length` value and other bugs came out from there.

@tkoomzaaskz I think that using a `probability` flag will only bloat our schemas, IMO is not necessary yet (?)

@Semigradsky could you run your tests against the `develop` branch?

I think [this is fixed now](https://github.com/pateketrueke/json-schema-faker/commit/8079b8d22e371cbc4de402348e6ae6875283267d) and it's time to release a new patch.

Sorry for the lag. :beers:

**Comment by Semigradsky** [comment]
@pateketrueke fine!
Now it is working as expected :+1:
