### ISSUE TITLE
travis build failing

### ISSUE THREAD

**Issue by ducin** [pateketrueke/json-schema-faker#46]
This is very suspicious. Until now everything was working fine. Today I bumped faker.js 2.1.3 -> 2.1.4 and suddenly, travis build crashed. So I reverted the commit (which retriggered the travis build) and it failed again. I got no idea on what's going on, but in https://travis-ci.org/pateketrueke/json-schema-faker/builds/65619706 I can see that there are some methods missing:
* TypeError: Object [object Object] has no method 'toHaveSchema'
* TypeError: Object [object Object] has no method 'toHaveType'

@pateketrueke do you have any idea what can this be connected with?

**Comment by pateketrueke** [comment]
It seems like jasmine-node is no longer requiring the spec `helpers.coffee`, I've added it manually and works again.

```coffee
# main-spec.coffee
require('./helpers')

fs = require('fs')
glob = require('glob')
jsfaker = require('../lib')

# ...
```

**Comment by whitlockjc** [comment]
Are you going to commit the fix?  I ask because I'm working on a PR and I don't want to include that fix if I don't need to, but I do need it to run the test suite.

**Comment by pateketrueke** [comment]
I've commited to `master`, please rebase again.

**Comment by whitlockjc** [comment]
Thanks a lot.

**Comment by whitlockjc** [comment]
I hate to be a bother but you committed to `master` yet you suggest we create PRs against `develop`.  Any reason you didn't commit there instead?

**Comment by pateketrueke** [comment]
You're right, I've published to `develop` too, was my fault. :beers:

**Comment by whitlockjc** [comment]
Thanks.  :)

**Comment by pateketrueke** [comment]
Not sure but I think this is solved.
