### ISSUE TITLE
Reference not found with $schema

### ISSUE THREAD

**Issue by omerts** [pateketrueke/json-schema-faker#52]
Hello,

If I use a ref inside my json schema, I get a "Reference not found: http://json-schema.org/draft-04/id#" error for the $schema def. 
The schema:
```json
{ "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items": 
   { "type": "object",
     "properties": 
      { "id": { "$ref": "id" },
        "name": { "$ref": "name" },
        "description": { "$ref": "description"  } },
    "required": [ "id", "name", "description" ] } }
```

Removing the $schema key, or remove the $refs, works, but I want to be able to keep both.

Thanks,
Omer

**Comment by pateketrueke** [comment]
How you're specifying those references?

Basically you can do this:

```js
var schema = {
  type: 'object',
  properties: {
    someValue: {
      $ref: 'otherSchema'
    }
  }
};

var refs = [
  {
    id: 'otherSchema',
    type: 'string'
  }
];

var sample = jsf(schema, refs);
```

Check out the README section about [using references](https://github.com/pateketrueke/json-schema-faker#using-references).

**Comment by omerts** [comment]
@pateketrueke 
It throws the error on this line:
```javascript
"$schema": "http://json-schema.org/draft-04/schema#"
```
Which I haven't used $ref on. Using refs without the above line, works perfectly. (I do something similar to the example)

**Comment by pateketrueke** [comment]
Schemas and references should have the same `$schema` key because that's how references works on JSON-Schema.

Of course, if both ref and schema have not `$schema` a default should be used for.

Default `$schema` if missing: `http://json-schema.org/schema#`

So, this works perfectly:

```js
var schema = { "type": "array",
  "items":
   { "type": "object",
     "properties":
      { "id": { "$ref": "id" },
        "name": { "$ref": "name" },
        "description": { "$ref": "description"  } },
    "required": [ "id", "name", "description" ] } };

var refs = [
  { "id": "id", "type": "string" },
  { "id": "name", "type": "string" },
  { "id": "description", "type": "string" }
];

var jsf = require('json-schema-faker');

console.log(JSON.stringify(jsf(schema, refs), null, 2));
```

Using the same `$schema` also works:

```js
var schema = { "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "array",
  "items":
   { "type": "object",
     "properties":
      { "id": { "$ref": "id" },
        "name": { "$ref": "name" },
        "description": { "$ref": "description"  } },
    "required": [ "id", "name", "description" ] } };

var refs = [
  { "$schema": "http://json-schema.org/draft-04/schema#", "id": "id", "type": "string" },
  { "$schema": "http://json-schema.org/draft-04/schema#", "id": "name", "type": "string" },
  { "$schema": "http://json-schema.org/draft-04/schema#", "id": "description", "type": "string" }
];
```

Any schema you use must share the same namespace (`$schema`) to resolve properly between them.

**Comment by ducin** [comment]
@omerts did you solve your problem? Do you have further questions?

**Comment by omerts** [comment]
I did, sorry for not closing. Thank you @pateketrueke :)

**Comment by ducin** [comment]
@omerts PS if you think we might extend our docs, so that it's easier for other people, please, submit a PR :)
