### ISSUE TITLE
Generate value based on another generate value

### ISSUE THREAD

**Issue by omerts** [pateketrueke/json-schema-faker#53]
Hello,

I have a schema, where the value of one property is oneOf different objects.  I need the oneOf to be selected according to a generated value in a different field. 
For example:
```json
  "exclusiveMinimum": true,
  "items": 
   { "type": "object",
     "properties": 
      { "id": { "$ref": "id" },
        "data_item_type": { "$ref": "data_item_type" },
        "preview": { "oneOf": [
                    { "type": "object",
                      "properties": 
                        { "name": { "$ref": "name" } } },
                    { "type": "object",
                      "properties": 
                        { "duration": { "type": "number" } } }
                   ]}...
```
I need the preview object to be selected according to the value in data_item_type.
Is it possible?

Thank you

**Comment by ducin** [comment]
As far as I understand, you need to make a relation between (sub)attributes within one schema.

And as far as I know, relative values are not supported by jsf yet #11. But the feature would be very welcome! We haven't agreed on the algorithm for doing it yet.

**Comment by omerts** [comment]
I see. Thank you :).

**Comment by ducin** [comment]
@omerts I close this one, since it's the same as #11.
