### ISSUE TITLE
Please update faker.js

### ISSUE THREAD

**Issue by omerts** [pateketrueke/json-schema-faker#55]
This project is very helpful to us. We need the new faker.js generators, such as name.jobTitle.

**Comment by ducin** [comment]
@omerts What do you mean by updating faker generators? Recently, faker.js `3.0.0` has been released and so json-schema-faker `0.2.0` has been released (basing on faker.js `3.0.0`). I checked and faker 3.0.0 is the latest release.

Please provide more information on what exactly do you expect?

**Comment by omerts** [comment]
@ducim I am trying to use faker.jobDescriptor, faker.jobArea, and faker.jobType, and I am getting the following error:
```
Error: unknown faker-generator for "name.jobDescriptor
```

**Comment by ducin** [comment]
@omerts which faker.js version are those generators available in?

**Comment by pateketrueke** [comment]
This actually works:

```js
var jsf = require('json-schema-faker');

var schema = {
  type: 'string',
  faker: 'name.jobDescriptor'
};

console.log(jsf(schema));
```

**Comment by omerts** [comment]
Sorry I was in an older json-schmea-faker version. Thanks for the great work!
