### ISSUE TITLE
chance: "url" fails

### ISSUE THREAD

**Issue by braco** [pateketrueke/json-schema-faker#6]
But it should work:
http://chancejs.com/#url

You might need a version bump, 0.7.1 is latest

**Comment by pateketrueke** [comment]
It seems you're using a lot this module, yay!

Could you switch to the develop branch instead of using the npm-registry?

That would helps on solving issues quicker without publishing minor changes to npm.

**Comment by braco** [comment]
Sure am, great job on this package! I switched.

**Comment by braco** [comment]
Thanks also for being so prompt.
